# 일차식과 일차 함수
* 선형대수학 : 선형방정식의 해를 구하기 위한 학문 -> 일차식이나 일차 함수를 공부하는 학문
> [wikipedia]
> 
>선형대수학(線型代數學, 영어: linear algebra)은 벡터 공간, 벡터, 선형 변환, 행렬, 연립 선형 방정식 등을 연구하는 대수학의 한 분야이다.
>현대 선형대수학은 그중에서도 벡터 공간이 주 연구 대상이다. 추상대수학, 함수해석학에 널리 쓰이고 있다.

* 일차식: 가장 높은 차수가 1인 다항식   
<img src ="https://user-images.githubusercontent.com/74705142/112970502-39ba7480-9189-11eb-9af6-a67092df1959.png" width="300" align="left">  

* 일차함수: 가장 높은 차수가 1인 x에 대한 f(x)  

<img src ="https://user-images.githubusercontent.com/74705142/112971220-f9a7c180-9189-11eb-9a3d-6b7b74936432.png" align="left">   

# 행렬과 벡터
* 행렬 : 수를 직사각형의 형태로 나열한 것  

<img src="https://user-images.githubusercontent.com/74705142/112972467-40e28200-918b-11eb-9e0c-4a1ec299920b.png" align="left">

* 벡터 
  * Computers: 행이나 열 개수가 1인 행렬. 원소가 한개의 index나 subscript에 나열할 수 있는 데이터의 배열 
  * Mathematics/Physics : 크키와 방향을 가진 물리량 ex)위치- 원점에서부터 동쪽으로 40m   
    (스칼라: 힘만 있고 방향은 없는 양. 시간, 온도, 무게 등)
  - n 차원의 열벡터 : (n,1)행렬 
  - n 차원의 행벡터 : (1,n)행렬  
  
<img src="https://user-images.githubusercontent.com/74705142/112974877-eb5ba480-918d-11eb-9c81-d1eb36e1c778.png" align="left">

   
 * 벡터의 연산  
  
<img src="https://user-images.githubusercontent.com/74705142/113100331-3cbf6e80-9236-11eb-992b-3527631da9b9.png" align="left"> 

# numpy로 행렬만들기

In [16]:
import numpy as np
import pandas as pd

## 원하는 값을 입력하여 행렬 만들기

In [3]:
A = np.array([
    [1,-1,2],
    [3,2,2],
    [4,1,2],
    [7,5,6]
])

# 4 by 3 행렬의 생성
A

array([[ 1, -1,  2],
       [ 3,  2,  2],
       [ 4,  1,  2],
       [ 7,  5,  6]])

In [4]:
B= np.array([
    [0,1],
    [-1,3],
    [5,2]
])

# 3 by 2 행렬의 생성
B

array([[ 0,  1],
       [-1,  3],
       [ 5,  2]])

 ## random함수를 이용하여 행렬만들기

In [21]:
# np.random.rand(m,n)
# rand: Create an array of the given shape and populate it with random samples from a uniform distribution

c = np.random.rand(3,5)  
c


array([[0.77301133, 0.22177578, 0.80743541, 0.06354729, 0.16823921],
       [0.84150794, 0.39618233, 0.96804258, 0.54559948, 0.99007003],
       [0.04020046, 0.4368406 , 0.57511259, 0.57052428, 0.95010771]])